### ISSUE TITLE
Pasting size on text not updating it's height

### ISSUE THREAD

**Issue by highvoltaged** [ajilderda/Sketch-Copy-Paste-Position-Size#4]
Create a textbox with a few words in it.
Copy an object with a much smaller width
Paste width over textbox
The width will be copied over, but the textbox's height won't update to the new content

Check out "Textbox fit content" plugin, you might be able to copy the code from there

Thanks Matt

**Comment by highvoltaged** [comment]
Thanks for the quick response!

Yeah i guessed something like that. Anyway i can just use that Textbox fit plugin after it, so no  problem.

I use your plugin a million times a day, thanks!

**Comment by ajilderda** [comment]
I fixed it by calling the `fitTextFrame` function before and after the layer was resized. It's not elegant, but works! You can download the updated version here:
https://github.com/ajilderda/Sketch-Copy-Paste-Position-Size/archive/master.zip

Great to hear you find it useful!

**Comment by highvoltaged** [comment]
Tried it, and seems to be working perfectly!
Thanks a bunch!!!
