### ISSUE TITLE
!!!Not working after Sketches new Update

### ISSUE THREAD

**Issue by disdontwork** [ajilderda/Sketch-Copy-Paste-Position-Size#7]
It is randomly pasting dimensions but not copying any dimensions.

**Comment by birockr** [comment]
Same here.

**Comment by ajilderda** [comment]
This should be solved with the newest version:
https://github.com/ANGIstudio/Copy-Paste-Position-Size/archive/master.zip

Can you let me know if this is the case?

**Comment by birockr** [comment]
Working fine now. Thank you!
