### ISSUE TITLE
Paste X Y not working correctly (Sketch Version 67.2)

### ISSUE THREAD

**Issue by accrossthesea** [ajilderda/Sketch-Copy-Paste-Position-Size#8]
When I paste my values to a new element/layer, it sends the layer to the artboard I originally copied it from. Does that make sense? It's relative to the whole doc, not just the canvas I originally copied.

Is there anything that can fix this? It used to work fine.

Hope you can help!

**Comment by accrossthesea** [comment]
![Untitled-1](https://user-images.githubusercontent.com/53853899/89135781-37a90300-d573-11ea-98ac-ada12267b4fd.gif)

**Comment by jayliu50** [comment]
Yeah, it seems to be using the absolute X and Y, not the X and Y relative to the artboard or symbol.

**Comment by ajilderda** [comment]
Hi guys, this should be fixed with the latest release. Can you please check and report back?:
https://github.com/ajilderda/Sketch-Copy-Paste-Position-Size/releases
